MedicDiary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('centralapp.urls')),
    path('', include('doctor.urls')),
    path('', include('patient.urls')),
]

centralapp/urls.py
from . import views
from django.urls import path

app_name = 'centralapp'
urlpatterns = [

    path('',views.mainpage,name='mainpage'),
    path('About_us/',views.About_us,name ='About_us'),
    path('Aids/',views.Aids,name ='Aids'),
    path('Cancer/',views.Cancer,name ='Cancer'),
    path('Covid-19/',views.Covid_19,name ='Covid_19'),
    path('Diabetes/',views.Diabetes,name ='Diabetes'),
    path('FAQS/',views.FAQS,name ='FAQS'),
    path('Heart_disorder/',views.Heart_disorder,name ='Heart_disorder'),
    path('medical_practitioners/How_to_use',views.doc_how_to_use,name ='doc_how_to_use'),
    path('friends-and-family/How_to_use',views.patients_how_to_use,name ='patients_how_to_use'),
    path('Hypertension/',views.Hypertension,name ='Hypertension'),
    path('Inside_health_records/',views.Inside_health_records,name ='Inside_health_records'),    ]

doctor/urls.py
from . import views
from django.urls import path

app_name = 'doctor'
urlpatterns = [
      path('registerpage/',views.registerpage,name ='registerpage'),
       path('signup/',views.signup, name ='signup'),
         path('logind/',views.loginn, name ='logind'),
          path('myPatients/', views.myPatients, name='myPatients'),
      #     path('doctorProfile/', views.doctorProfile, name='doctorProfile'),
          path('addpatient/', views.addpatient, name='addpatient'),
          path('doctorRecords/<str:p>', views.doctorRecords, name='doctorRecords'),
           path('addRecord/', views.addRecord, name='addRecord'),
            path('newReport/', views.newReport, name='newReport'),
 

    path('doctorprofile/', views.doctor_profile, name='doctor_profile'),
   
   
   
    # path('doclogin/',views.doclogin,name ='doclogin'),
    # path('docregister/',views.docregister,name ='docregister')
]

patient/urls.py
from . import views
from django.urls import path

app_name = 'patient'
urlpatterns = [

    path('Medications/', views.medications, name='medications'),
    path('LabReports/', views.labreports, name='labreports'),
    path('patientProfile/', views.patientProfile, name='patientProfile'),
    path('patientRecords/', views.patientRecords, name='patientRecords'),
    path('personalNotes/', views.personalNotes, name='personalNotes'),
    
    
    # path('login/',views.login,name ='login'),
    path('registerpage/',views.registerpage,name ='registerpage'),
    path('signup/',views.signup, name ='signup'),
    path('loginp/',views.loginn, name ='loginp'),
    path('logout/',views.logout, name ='logout'),
    path('addnotes/',views.addnotes, name ='addnotes'),

]

doctor/models.py
from django.db import models

# Create your models here.
class doc_details(models.Model):
    usertype=models.CharField(max_length=100,default="doctor")
    fname=models.CharField(max_length=100)
    lname=models.CharField(max_length=100)
  
    username=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
  
    
class patient_doc_config(models.Model):
    patient_username=models.CharField(max_length=100)
    doctor_username=models.CharField(max_length=100)
    auth_key=models.CharField(max_length=100)

class records(models.Model):
    doctor_username=models.CharField(max_length=100,default="sdk")
    patient_username=models.CharField(max_length=100,default="skdjks")
    diagnosis=models.CharField(max_length=100)
    doctor_notes=models.TextField(max_length=1000)
    medications=models.TextField(max_length=1000)

doctor/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .models import doc_details,patient_doc_config,records
from django.contrib.sessions.models import Session
from patient.models import patient_details

# Create your views here.
def doctor_profile(request):
    return render(request,'doctor/doctor_profile.html')

def doctorRecords(request):
    return render(request, 'doctor/doctor_records.html')
    
def registerpage(request):
    return render(request,'doctor/register.html')




def signup(request):
    if request.method=="POST":
        fname=request.POST['fname']
        lname=request.POST['lname']
        
        username=request.POST['username']
        password=request.POST['password']
        email=request.POST['email']
       


        if len(username)>15:
            messages.error(request,'length of username should be less than15')
            return redirect('patient:registerpage')
        
        

        myuser=User.objects.create_user(username,email,password)
        myuser.first_name=fname
        myuser.last_name=lname
       
        new_doc=doc_details()
        new_doc.lname=lname
        new_doc.fname=fname
        new_doc.username=username
        new_doc.email=email
        new_doc.save()
        
        myuser.save()
              
        newPatient=patient_doc_config()
        newPatient.patient_username="sample_pusername"
        newPatient.doctor_username=username
        newPatient.auth_key=123
        newPatient.save()


        messages.success(request, 'Form submission successful')
        return redirect('/')
       

    else :
        return HttpResponse('404-not found')


def loginn(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            print("innn")
            request.session["username_d"]=username
            return render(request,'doctor/doctor_profile.html',{"username":username}) 

        else :
            print("invalid credentials")
            return render(request,'centralapp/mainpage.html')


        return HttpResponse('login')



    else:
        return HttpResponse('404-not found')

def myPatients(request):
    username=request.session["username_d"]
    if len(patient_doc_config.objects.filter(doctor_username=username))!=0:
        pat=patient_doc_config.objects.filter(doctor_username=username)
        return render(request, 'doctor/mypatients.html',{"patients":pat})

    else :
        return render(request, 'doctor/mypatients.html',{"patients":"add patients"})

    
    return render(request, 'doctor/mypatients.html',{"username":username})

def doctorProfile(request):
    return render(request, 'doctor/doctor_profile.html')

def addpatient(request):
    if request.method=="POST":
        p_username=request.POST['username']
        accesscode=request.POST['accesscode']

        if len(patient_details.objects.filter(username=p_username))!=0:
            pat=patient_details.objects.get(username=p_username)
            if  pat.auth_key==accesscode:

                newPatient=patient_doc_config()
                newPatient.patient_username=p_username
                newPatient.doctor_username=request.session["username_d"]
                newPatient.auth_key=accesscode
                newPatient.save()
                redirect('doctor:myPatients')
            else :
                redirect('doctor:myPatients')
                messages.error(request,'access code did not match')
        else:
             redirect('doctor:myPatients')
             messages.error(request,'username does not exist')




        return redirect('doctor:myPatients')


    else:
         return HttpResponse('404-not found')

def doctorRecords(request,p):
    request.session["username_p"]=p
    return render(request, 'doctor/doctor_records.html')
    


def addRecord(request):
    return render(request,'doctor/report.html')

def newReport(request):
    diagnosis=request.POST['diagnosis']
    doctor_notes=request.POST['doctor_notes']
    medications=request.POST['medications']

    new_record=records()
    new_record.diagnosis=diagnosis
    new_record.doctor_notes=doctor_notes
    new_record.medications=medications
    new_record.doctor_username=request.session["username_d"]
    new_record.patient_username=request.session["username_p"]
    new_record.save()

    return redirect('doctor:doctorRecords', p_username=request.session["username_p"])

doctor/templates/doctor/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
		integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Pacifico" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cinzel" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Grandstander" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu" />

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
		integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
		integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
		integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
		crossorigin="anonymous"></script>
	<script src="https://kit.fontawesome.com/032a738741.js" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="{% static 'doctor/css_files/style.css' %}">
	<link rel="icon" type="image/png" href="{% static 'doctor/Images/icon.png' %}" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
	<script src="{% static 'doctor/js/app.js' %}"></script>
	<!--<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>-->
	<title>MedicDiary</title>
</head>

<body style="background: #f7f7ee">
	<script>
		AOS.init();
		document.getElementById("defaultOpen").click();
	</script>
	<nav class="navbar navbar-expand-lg navbar-light nav-bg" id="navstyle">
		<a class="navbar-brand" href="{% url 'centralapp:mainpage' %}"
			style="font-family: Cinzel; font-size: 40px !important; color: white;">
			<img src="{% static 'doctor/Images/icon.png' %}" width="50" height="50" class="d-inline-block align-top"
				alt="" loading="lazy">
			MedicDiary
		</a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-size:20px; ">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item active">
					<a class="nav-link" href="#" style="color: rgb(0, 0, 0)"> Sign In </a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="#" style="color: rgb(0, 0, 0)"> Sign Up </a>
				</li>
			</ul>
		</div>
	</nav>

	<div id="sidebar">
		<div class="toggle-btn" onclick="toggleSideBar()">
			<span style='font-size:20px;'>&#9776;</span>
		</div>

		<ul>
			<a class="tablinks" href="{% url 'doctor:myPatients' %}">
				<li>My Patients</li>
			</a>
			<a class="tablinks" href="{% url 'doctor:doctor_profile' %}">
				<li>My Profile</li>
			</a>
		</ul>
	</div>
	<!-- <div id="main-content">
		<div class="tabcontent" id="myPatients">
			Hey this is my patients page holla,aa,l,c
		</div>
		<div class="tabcontent" id="myProfile">
			Hey this is my profile page
		</div>
	</div>
	 -->
	{% block doctorbase %}
	{% endblock %}
		
	<!-- Footer -->
	<footer class="page-footer footer font-small mdb-color" style="background:linear-gradient(90deg, #24a19c,#cedebd);">
		<div class="row text-center ml-5 text-md-left mt-3">
			<hr class="w-100 clearfix d-md-none">
			<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
				<h6 class="text-uppercase mb-2 ">Know-hows</h6>
				<p>
					<a href="{% url 'centralapp:Inside_health_records' %}" class="useful_links">What's in my health
						record</a><br>
					<a href="{% url 'centralapp:patients_how_to_use' %}" class="useful_links">How to use my health
						record</a><br>
					<a href="{% url 'centralapp:doc_how_to_use' %}" class="useful_links">How to use the health record
						(for doctors)</a><br>
					<a href="{% url 'centralapp:FAQS' %}" class="useful_links">FAQs</a><br>
				</p>
			</div>
			<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
				<h6 class="text-uppercase mb-2 font-weight-bold"> Other useful links</h6>
				<div class="no-bullet-list two-column-list">
					<a href="{% url 'centralapp:Covid_19' %}" class="useful_links">Covid-19 checkpoints</a><br>
					<h6 class="mt-2 font-weight-bold">Learn about diseases</h6>
					<ul>
						<li><a href="{% url 'centralapp:Cancer' %}" class="useful_links">Cancer</a><br></li>
						<li><a href="{% url 'centralapp:Aids' %}" class="useful_links">AIDS</a><br></li>
						<li><a href="{% url 'centralapp:Diabetes' %}" class="useful_links">Diabetes</a><br></li>
						<li><a href="{% url 'centralapp:Heart_disorder' %}" class="useful_links">Heart Disorders</a><br>
						</li>
						<li><a href="{% url 'centralapp:Hypertension' %}" class="useful_links">Hypertension</a><br></li>
					</ul>
				</div>
			</div>
			<hr class="w-100 clearfix d-md-none">
			<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3 no-bullet-list footer-style">
				<h6 class="text-uppercase mb-2 font-weight-bold">Our Team</h6>
				<ul>
					<li>Madhav Mittal<br></li>
					<li>HarshDeep Singh Kohli<br></li>
					<li>Lavish Bansal<br></li>
					<li>Shivangi Nayak</li>
				</ul>
				<a href="{% url 'centralapp:About_us' %}" class="useful_links" style="font-weight:bold">More about
					us</a>
			</div>
			<hr class="w-100 clearfix d-md-none ">
			<div class="col-md-3 col-lg-3 col-xl-3 mr-5 mt-3 footer-style">
				<h6 class="text-uppercase mb-2 font-weight-bold ">Contact</h6>
				<p>
					<i class="fa fa-home mr-3"></i>IIT(BHU), Varanasi, UP, India
				</p>
				<p>
					<i class="fa fa-envelope mr-3 "></i> madhav.mittal.mat19@itbhu.ac.in
				</p>
				<p>
					<i class="fa fa-phone mr-3"></i> +91 9039276236
				</p>

			</div>
		</div>
		<hr>
		<div class="row d-flex align-items-center footer-style">
			<!-- Grid column -->
			<div class="col-md-11 col-lg-11">
				<!--Copyright-->
				<p class="text-center">© 2020 Copyright:
					<strong> MedicDiary</strong>
				</p>
			</div>
		</div>
	</footer>

</body>

</html>

doctor/templates/doctor/doctorMainPage.html
{% extends 'doctor/base.html' %}

{% block doctor_base %}
{% load static %}

<!--THIS IS THE MYPROFILE PAGE-->
{% block doctormainpage %}
{% endblock %}
<div class="container" id="main-content">
    <div class="tabcontent" id="myProfile" style="display:block;">
        <h1 style="font-family:'Ubuntu';font-size: 3rem;text-align: center; color: rgb(92, 46, 13); ">My Profile </h1>
        <div class="container">
            <button class="edit-option-buttons" style="font-size: 18px; float: right;">
                <a href="#"> Edit your profile </a>
            </button>
        </div>
        <div style="display: flex;justify-content: center;">
            <div class="row my-4 profile-box-info justify-content-around" style="width: fit-content">
                <div class="col-sm-2 p-2 col-lg-2 p-2" style="margin-right: 20px;">
                    <img src="{% static 'doctor/Images/profile_pic.png'%}" max-width="80%" alt="">
                </div>
                <div class="col-sm-6 col-lg-6 p-2 " style="margin-left: 50px;">
                    <div class="profile-content">
                        <h3>General Info</h3>
                        <b>Name:</b> Dr. Randeep Guleria <br>
                        <b>Username:</b> whatever <br>
                        <b>Email Address:</b> xyz@gmail.com
                    </div>
                    <button class="edit-option-buttons" style="margin-top: 30px;">Edit Profile Picture</button>
                </div>
            </div>
        </div>
        <div class="row my-10">
            <div class="col-sm-5 col-lg-5 p-2 ml-auto mr-auto">
                <div class="profile-box-info">
                    <div class="profile-content">
                        <h3>Educational Qualifications</h3>
                        <p>
                            <b>Graduation College: </b> AIIMS Delhi <br>
                            <b>Specialisation:</b> XYZ <br>
                            <b>Super Specialisation:</b> ABC <br>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 p-2 col-lg-5 ml-auto mr-auto">
                <div class="profile-box-info ">
                    <div class="profile-content">
                        <h3>Experience</h3>
                        <p>
                            Apollo, Sarita Vihar<br>
                            Max Super Speciality hospital, Vaishali<br>
                            Some other hospital<br>
                            And some other
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row my-4">
            <div class="col-sm-5 p-2 col-lg-5 ml-auto mr-auto">
                <div class="profile-box-info ">
                    <div class="profile-content">
                        <h3>Availability</h3>
                        <p>
                            <b>XYZ clinic: </b> 7-8pm Sundays <br>
                            <b>ABC hospital:</b> 11am-12pm Wed Fri <br>
                            <b>PQR hospital:</b> 4-5pm Mon Thurs <br>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-5 p-2 col-lg-5 ml-auto mr-auto my-4">
                <div class="profile-box-info ">
                    <div class="profile-content">
                        <h3>Speciality</h3>
                        <p>
                            If the doctor is a surgeon, then he could mention what kind of surgeries he specialises in.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>





    <!--This is the beginning of the myPatients Page-->


    <div class="tabcontent" id="myPatients">
        <div>
            <h1 style="text-align: center;">Patient's List</h2>
                <button class="edit-option-buttons" style="float:right">
                    <a href="#" data-toggle="modal" data-target="#accessmodal"> Add a new patient </a>
                </button>
        </div>
        <div class="container" style="margin: auto;">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Access Code</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Options</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">12efc8%2</th>
                        <td>Harshdeep</td>
                        <td>Singh</td>
                        <td><button class="edit-option-buttons"><a
                                    href="{% url 'doctor:doctorRecords' %}">Edit</a></button></td>
                    </tr>
                    <tr>
                        <th scope="row">1lefc8%2</th>
                        <td>Lavish</td>
                        <td>Bansal</td>
                        <td><button class="edit-option-buttons"><a
                                    href="{% url 'doctor:doctorRecords' %}">Edit</a></button></td>
                    </tr>
                    <tr>
                        <th scope="row">02efc8%2</th>
                        <td>Madhav</td>
                        <td>Mittal</td>
                        <td><button class="edit-option-buttons"><a
                                    href="{% url 'doctor:doctorRecords' %}">Edit</a></button></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="modal fade" id="accessmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-notify modal-warning" role="document">
                <!--Content-->
                <div class="modal-content">
                    <!--Header-->
                    <div id="signincard" class="card">
                        <div id="cardhead" class="card-header bg-warning mb-2">
                            <div class="card-title text-center h4">Add a Patient</div>
                        </div>

                        <!-- Input Fields -->
                        <form action="{% url 'patient:loginp' %}" method="POST">
                            {% csrf_token %}
                            <input type="text" id="accessCode" class="form-control mb-2"
                                placeholder="Enter the access code" name="accessCode">
                            <!-- Login Button -->
                            <div class="text-center">
                                <button class="btn my-2" id="submit-btn" type="submit">Submit</button>
                            </div>
                        </form>

                    </div>
                </div>
                <!--/.Content-->
            </div>
        </div>
    </div>
</div>


{% endblock %}

doctor/templates/doctor/doctor_base.html
{% extends 'doctor/base.html' %}

{% block body %}
{% load static %}
<div id="sidebar">
    <div class="toggle-btn" onclick="toggleSideBar()">
        <span style='font-size:20px;'>&#9776;</span>
    </div>
    <a href="#" class="btn-close" onclick="closeSideBar()">&times;</a>

    <ul>
        <li><a href="{% url 'doctor:myPatients' %}">My Patients</a></li>
        <li><a href="{% url 'doctor:doctorProfile' %}">My Profile</a></li>
        <li><a href="#">Back to homepage</a></li>

    </ul>

</div>

{% block doctor_base %}
{% endblock %}


{% endblock %}

doctor/templates/doctor/doctor_records.html
{% extends 'doctor/base.html' %}

{% block doctorbase %}
{% load static %}

<div class="container" id="main-content" >
    <div class="row dashboard-content">
        <h2>Current Medication </h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <a href="#">View more</a>

    </div>
    <div class="row dashboard-content">
        <h2>Recent Lab reports </h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <a href="#">View more</a>

    </div>
    <div class="row dashboard-content">
        <h2>Patient's personal notes</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
    </div>
   


    <div class="container">
        <button class="edit-option-buttons" style="font-size: 18px;">
            <a href="{% url 'doctor:addRecord' %}"> Add a new record </a>
        </button>
    </div>
    
</div>
{% endblock %}

doctor/templates/doctor/patientList.html
{% extends 'doctor/base.html' %}
{% block doctorbase %}
<div class="tabcontent" id="myPatients">
<div id="main-content">
<div>
    <h1 style="text-align: center;">Patient's List</h2>
        <button class="edit-option-buttons" style="float:right">
            <a href="#" data-toggle="modal" data-target="#accessmodal" > Add a new patient </a>
        </button>
</div>
<div class="container" style="margin: auto;">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                
                <th scope="col">Patient Username</th>
             
                <th scope="col">Options</th>
            </tr>
        </thead>
        <tbody>
            
            {%for i in patients%}
            <tr>
                <td>{{i.patient_username}}</td>
                <td><button class="edit-option-buttons"><a href="{% url 'doctor:doctorRecords' p=i.patient_username %}">Edit</a></button></td>
            </tr> 
            {% empty %}
            <td>Do this in empty condition</td> 
           {%endfor%}

           

          

          
          
        </tbody>
    </table>
    <div>
        {% for message in messages%}
        <h3>{{message}}</h3>
        {% endfor %}
    </div>

</div>
<div class="modal fade" id="accessmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-notify modal-warning" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Header-->
            <div id="signincard" class="card">
                <div id="cardhead" class="card-header bg-warning mb-2">
                    <div class="card-title text-center h4" >Add a Patient</div>
                </div>

                <!-- Input Fields -->
                <form action="{% url 'doctor:addpatient' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" id="accessCode" class="form-control mb-2" placeholder="patient_username"
                        name="username">
                 <input type="text" id="accessCode" class="form-control mb-2" placeholder="Enter the access code"
                        name="accesscode">
                    <!-- Login Button -->
                    <div class="text-center">
                        <button class="btn my-2" id="login" type="submit">Submit</button>
                    </div>
                </form>
               
            </div>
            
        </div>
        <!--/.Content-->
    </div>
</div>
</div>
</div>


{% endblock %}

doctor/templates/doctor/report.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form  action="{% url 'doctor:newReport' %}" method="POST">
      {% csrf_token %}
      <label for="">diagnosis:</label>
      <input type="text" name="diagnosis" value=""><br>
      <label for="">doctor notes:</label>
      <input type="text" name="doctor_notes" id=""><br>
      <label for="">medications:</label>
      <input type="text" name="medications" id=""><br>
      <label for="">submit:</label>
      <input type="submit" name="" id="">
    </form>
  </body>
</html>