MedicDiary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('centralapp.urls')),
    path('', include('doctor.urls')),
    path('', include('patient.urls')),
]

centralapp/urls.py
from . import views
from django.urls import path

app_name = 'centralapp'
urlpatterns = [

    path('',views.mainpage,name='mainpage'),
    path('About_us/',views.About_us,name ='About_us'),
    path('Aids/',views.Aids,name ='Aids'),
    path('Cancer/',views.Cancer,name ='Cancer'),
    path('Covid-19/',views.Covid_19,name ='Covid_19'),
    path('Diabetes/',views.Diabetes,name ='Diabetes'),
    path('FAQS/',views.FAQS,name ='FAQS'),
    path('Heart_disorder/',views.Heart_disorder,name ='Heart_disorder'),
    path('medical_practitioners/How_to_use',views.doc_how_to_use,name ='doc_how_to_use'),
    path('friends-and-family/How_to_use',views.patients_how_to_use,name ='patients_how_to_use'),
    path('Hypertension/',views.Hypertension,name ='Hypertension'),
    path('Inside_health_records/',views.Inside_health_records,name ='Inside_health_records'),    ]

doctor/urls.py
from . import views
from django.urls import path

app_name = 'doctor'
urlpatterns = [
      path('registerpage/',views.registerpage,name ='registerpage'),
       path('signup/',views.signup, name ='signup'),
         path('logind/',views.loginn, name ='logind'),
          path('myPatients/', views.myPatients, name='myPatients'),
      #     path('doctorProfile/', views.doctorProfile, name='doctorProfile'),
          path('addpatient/', views.addpatient, name='addpatient'),
          path('doctorRecords/<str:p>', views.doctorRecords, name='doctorRecords'),
           path('addRecord/', views.addRecord, name='addRecord'),
            path('newReport/', views.newReport, name='newReport'),
 

    path('doctorprofile/', views.doctor_profile, name='doctor_profile'),
   
   
   
    # path('doclogin/',views.doclogin,name ='doclogin'),
    # path('docregister/',views.docregister,name ='docregister')
]

patient/urls.py
from . import views
from django.urls import path

app_name = 'patient'
urlpatterns = [

    path('Medications/', views.medications, name='medications'),
    path('LabReports/', views.labreports, name='labreports'),
    path('patientProfile/', views.patientProfile, name='patientProfile'),
    path('patientRecords/', views.patientRecords, name='patientRecords'),
    path('personalNotes/', views.personalNotes, name='personalNotes'),
    
    
    # path('login/',views.login,name ='login'),
    path('registerpage/',views.registerpage,name ='registerpage'),
    path('signup/',views.signup, name ='signup'),
    path('loginp/',views.loginn, name ='loginp'),
    path('logout/',views.logout, name ='logout'),
    path('addnotes/',views.addnotes, name ='addnotes'),

]

centralapp/models.py
from django.db import models

# Create your models here.

centralapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
# import requests
# from bs4 import BeautifulSoup
# Create your views here.

def mainpage(request):
    # page = request.get('')
    # soup = BeautifulSoup(page.text,'html.parser')
    # https://www.niams.nih.gov/health-topics/all-diseases
    # https://www.cdc.gov/diseasesconditions/index.html
    # https://www.pinehurstmedical.com/internalmedicine/internal-medicine-diseases-disorders-a-syndromes/
    # https://familydoctor.org/diseases-and-conditions/


    return render(request,'centralapp/mainpage.html')

def About_us(request):
    return render(request,'centralapp/about_us.html')
def Cancer(request):
    return render(request,'centralapp/cancer.html')
def Covid_19(request):
    return render(request,'centralapp/Covid_19.html')
def Diabetes(request):
    return render(request,'centralapp/diabetes.html')
def FAQS(request):
    return render(request,'centralapp/faqs.html')
def Heart_disorder(request):
    return render(request,'centralapp/heart_disorder.html')
def doc_how_to_use(request):
    return render(request,'centralapp/how_to_use_Doctor.html')
def patients_how_to_use(request):
    return render(request,'centralapp/how_to_use_User.html')
def Hypertension(request):
    return render(request,'centralapp/hypertension.html')
def Inside_health_records(request):
    return render(request,'centralapp/inside_health_records.html')
def Aids(request):
    return render(request,'centralapp/aids.html')

centralapp/templates/centralapp/Covid_19.html
{% extends 'centralapp/base.html' %}
{% load static %}
{% block body %}
<div class="typewriter">Corona Checkpoints.</div>
<div class="corona-subhead" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="1800">Keep the following things in mind.<br></div>
<div class="row cards" style="background: #faf3dd" data-aos="flip-up" data-aos-duration="1500">
	<div class="col-lg-5">
       <img class="covid-img" src="{% static 'centralapp/Images/wear_mask.jpg' %}">		
	</div>
	<div class="col-lg-7 paragraph">
		<h3 style="color: #c26565; font-weight: bold">A mask is a must.</h3><br>
		Always remember to wear a mask. Also ensure your mouth and nose are properly covered by the mask.
	</div>
</div>
<div class="row cards" style="background: #d2f6c5" data-aos="flip-up" data-aos-duration="1500">
	<div class="col-lg-7 paragraph">
		<h3 style="color: #206a5d; font-weight: bold" >Wash, wash and wash again..</h3><br>
       	Keep washing your hands at regular intervals. Spend at least 20 seconds rubbing to ensure that you cover all the nooks and corners.
	</div>
	<div class="col-lg-5">
		<img class="covid-img" src="{% static 'centralapp/Images/wash_hands.jpg' %}">
	</div>
</div>
<div class="row cards" style="background: #faf3dd" data-aos="flip-up" data-aos-duration="1500">
	<div class="col-lg-5">
       <img class="covid-img" src="{% static 'centralapp/Images/social_distance.jpeg' %}">		
	</div>
	<div class="col-lg-7 paragraph">
		<h3 style="color: #c26565; font-weight: bold">Remember the 6 Feet Rule.</h3> <br>
		Always ensure a minimum gap of 2 meters (or 6 feet) between you and others.
		This ensures that the droplet spread of this disease is minimised.
	</div>
</div>
<div class="row cards" style="background: #d2f6c5" data-aos="flip-up" data-aos-duration="1500">
	<div class="col-lg-7  paragraph">
		<h3 style="color: #206a5d; font-weight: bold">Sneeze... But ensure your mouth is covered</h3><br>
       	Follow the right etiquettes while coughing and sneezing. Always use a tissue or a cloth to cover your mouth while sneezing. If a tissue is not available, use your elbow to cover your mouth.
	</div>
	<div class="col-lg-5">
		<img class="covid-img" src="{% static 'centralapp/Images/sneeze.png' %}">
	</div>
</div>
<div class="row cards" style="background: #faf3dd" data-aos="flip-up" data-aos-duration="1500">
	<div class="col-lg-5">
       <img class="covid-img" src="{% static 'centralapp/Images/sanitiser.PNG' %}">		
	</div>
	<div class="col-lg-7 paragraph">
		<h3 style="color: #c26565; font-weight: bold">Always keep a sanitiser handy</h3> <br>
		Remember to thoroughly sanitise your hands after you touch any surface.
		The picture on the left shows how to use a sanitiser correctly.
	</div>
</div>
<div class="row cards" style="background: #d2f6c5" data-aos="flip-up" data-aos-duration="1500">
	<div class="col-lg-7  paragraph">
		<h3 style="color: #206a5d; font-weight: bold">Watch out for symptoms</h3><br>
       	Check if you or your family members have any of the following symptoms. If you suspect chances of having come in contact with a Coronavirus patient, seek medical help immediately. 
	</div>
	<div class="col-lg-5">
		<img class="covid-img" src="{% static 'centralapp/Images/covid_symptoms.jpg' %}">
	</div>
</div>


{% endblock %}

centralapp/templates/centralapp/about_us.html
{% extends 'centralapp/base.html' %}
{% load static %}
{% block body %}
<!-- <div class="parallax"></div> -->
<div class = "about_us_headline" data-aos="fade-up" data-aos-duration="2000">
	<h1 class="display">About medicdiary</h1>
	<p class="p_display">Providing a hassle-free environment to manage your health records.<br><br> We at MedicDiary believe that maintaining health records should be as simple as clicking a button<br></p>
	<p class="p_display" style="font-size:1.5em; color: #30475e;font-weight: bold;">MedicDiary lets you control your health information securely, in one place.</p>
</div>
<div class="container-fluid">
<div class="main_container row" data-aos="fade-down" data-aos-duration="1500">
	
	<div class="col-lg-5" data-aos="fade-left" data-aos-duration="1000">
		<img class="bhu_image" src="{% static 'centralapp/Images/bhu.jpeg' %}">
	</div>
	<div class="col-lg-7 paragraph" data-aos="fade-right" data-aos-duration="1000">
		We are a group of enthusiatic sophomores studying at IIT(BHU), pursuing Mathematics and Computing as our major field of study. We aim to provide a very user friendly platform to manage one's medical records.<br>
	</div>	
</div>
<div style="text-align: center;">
	<h1 class="display" data-aos="fade-down" data-aos-duration="1000">Our Team</h1>
	<div class="team" data-aos="fade-down" data-aos-duration="1200">
		<h2> The Frontend Team</h2>
		<ul>
			<li><a href="#"> Lavish Bansal </a></li>
			<li><a href="#"> Shivangi Nayak </a></li>
		</ul>
	</div>
	
	<div class="team" data-aos="fade-down" data-aos-duration="1200">
		<h2> The Backend Team</h2>
		<ul>
			<li><a href="#"> Madhav Mittal </a></li>
			<li><a href="#"> HarshDeep Singh Kohli </a></li>
		</ul>
	</div>
	
	
</div>
</div>
<div class="parallax"></div>
{% endblock %}

centralapp/templates/centralapp/how_to_use_Doctor.html
{% extends 'centralapp/base.html' %}
{% block body %}
{% load static %}
<div class="container-fluid">
    <div class="row my-4">
        <div class="col-sm-8 p-2 ml-auto" >
            <div data-aos="fade-up" data-aos-duration="1000" >
                <img class="health-record-img" src="{% static 'centralapp/Images/howto_Doctor.jpg' %}">
            </div>
            <h1 class="head-pacifico">How to work with health records at MedicDiary</h1>
            <div class="howtodiv">
                
                <h2>Register</h2>
                    <p>The first step when beginning to use MedicDiary as a healthcare professional is to create an account at our website. 
                        While registering you will need to provide some educational and professional details which might be required for authentication purposes.
                    Once this step is completed, you can go on to manage your patients' records.  </p>
                    <br>
    
                    <h2>Enter the access code</h2>
                    <p>In order to access the health record of any of your patients, you are required to enter a verification
                        cum access code which is unique to every patient. On successful verification of the access code, you will be
                        given access to edit the health records of your patient(s).<br>
                        You can view and manage all your patients under the "My Patients" section.
                    </p>
                    <br>
                    <h2>Maintain your profile as a healthcare professional</h2>
                    <p>Under the "My Profile" section, you can edit and maintain your profile, add new qualifications or delete some 
                        previously entered data. Additionally you can also specify your availability timings and the corresponding hospitals.  
                    </p>
                    <br>
                    <h2>Security and Privacy</h2>
                    <p> At MedicDiary, we place a lot of trust in our healthcare providers, which is eventually essential for the right 
                        diagnosis and for the proper maintainence of a health record. Alongside, we also expect the healthcare providers to 
                        follow a general code of conduct for the maintainence of records available at MedicDiary, infringement of which
                        may lead to cancellation of your membership at MedicDiary.   
                    </p>
                
                
                
            </div>
        </div>

{% endblock %}

centralapp/templates/centralapp/mainpage.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Pacifico" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Cinzel" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Oswald"/>
	<link rel="stylesheet" href="{% static 'centralapp/css_files/style.css' %}">
	<link rel="icon" type="image/png" href="{% static 'centralapp/Images/icon.png' %}"/>                            
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<title>MedicDiary</title>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light sticky-top" id="navstyle" >
		<a class="navbar-brand" href="{% url 'centralapp:mainpage' %}" style="font-family: Cinzel; font-size: 40px !important; color: white;" >
			<img src="{% static 'centralapp/Images/icon.png' %}" width="44" height="44" class="d-inline-block align-top" alt="Logo" loading="lazy">
			MedicDiary
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"  aria-expanded="true" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>


		<div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-size:18px;width: 60em; ">

			<ul class="navbar-nav ml-auto" id="navbar-list-items">
				<li class="nav-item dropdown ">
					<a class="nav-link " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
						For you and <br>your family &#x25BC;
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'centralapp:Inside_health_records' %}">What's in my health record </a>
						<a class="dropdown-item" href="{% url 'centralapp:patients_how_to_use' %}">How to use my health record </a>
					</div>
				</li>

				<li class="nav-item dropdown ">
					<a class="nav-link " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
						For healthcare <br>professionals &#x25BC;
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'centralapp:doc_how_to_use' %}">How to use the health record</a>
					</div>
				</li>
				<li class="nav-item dropdown ">
					<a class="nav-link " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
						Know more <br>about diseases &#x25BC;
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'centralapp:Aids' %}">AIDS</a>
						<a class="dropdown-item" href="{% url 'centralapp:Cancer' %}">Cancer</a>
						<a class="dropdown-item" href="{% url 'centralapp:Heart_disorder' %}">Heart Disorders</a>
						<a class="dropdown-item" href="{% url 'centralapp:Hypertension' %}">Hypertension</a>
						<a class="dropdown-item" href="{% url 'centralapp:Diabetes' %}">Diabetes</a>
						<a class="dropdown-item" href="{% url 'patient:patientProfile' %}">Dashboard</a>
						<a class="dropdown-item" href="{% url 'doctor:doctor_profile' %}">Doctor Dashboard</a>

					</div>
				</li>
				<li class="nav-item">
					<a class="nav-link "  href="{% url 'centralapp:FAQS' %}">FAQs</a>
				</li>
				<li class="nav-item">
					<a class="nav-link"  href="{% url 'centralapp:About_us' %}">About us</a>
				</li>
				<li class="nav-item button2">
					<a class="nav-link " href="{% url 'centralapp:Covid_19' %}" >Covid-19 Checkpoints </a>
				</li>
				
				<li class="nav-item dropdown">
					<a class="nav-link " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
						Sign Up 
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'centralapp:Inside_health_records' %}">Patient</a>
						<a class="dropdown-item" href="{% url 'centralapp:patients_how_to_use' %}">Doctors</a>
					</div>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#" data-toggle="modal" data-target="#usermodal">Login</a>
				</li>
			</ul>
		</div>
	</nav>

	<section>
		<div class="hero img">
			<a href="{% url 'centralapp:Inside_health_records' %}" class="button" id="user" data-toggle="modal" data-target="#usermodal"> For you and your family </a>
			<a href="#" class="button" id= "doctor" data-toggle="modal" data-target="#doctormodal">For healthcare professionals </a>

			<img src="{% static 'centralapp/Images/bg2.jpg' %}">

			<h1 class="headline">One place for all <br> your health records. </h1>
			<p></p>
		</div>
	</section>
	<div class="modal fade" id="usermodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    	<div class="modal-dialog modal-notify modal-warning" role="document">
    		<!--Content-->
    		<div class="modal-content">
				<!--Header-->
				<div id="signincard" class="card" >
					<div id="cardhead" class="card-header bg-warning mb-2">
						<div class="card-title text-center h4">Sign In</div>
					</div>

					<!-- Input Fields -->
					<form action="{% url 'patient:loginp' %}" method="POST">
						{% csrf_token %}
					<input type="text" id="username" class="form-control mb-2" placeholder="Patient's Username" name="username">
					<input type="text" id="password" class="form-control" placeholder="Password" name= "password">

					<div class="text-md-right" >
						<small>Forgot <a href="#">Username/Password</a></small>
					</div>

					<!-- Login Button -->
					<div class="text-center">
						<button class="btn my-2" id="submit-btn" type="submit">Login</button>
					</div>
				</form>
					<hr>

					<div class="text-center">
						<span>New User? </span><a href="{% url 'patient:registerpage' %}">Create an account</a>
					</div>
				</div>
			</div>
    		<!--/.Content-->
		</div>
	</div>

	<div class="modal fade" id="doctormodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  		<div class="modal-dialog modal-notify modal-warning" role="document">
			<!--Content-->
    		<div class="modal-content">
				<!--Header-->
				<div id="signincard" class="card" >
					<div id="cardhead" class="card-header bg-warning mb-2">
						<div class="card-title text-center h4">Sign In</div>
					</div>

					<!-- Input Fields form -->
					<form action="{% url 'doctor:logind' %}" method="POST">
						{% csrf_token %}
					<input type="text" id="username" class="form-control mb-2" placeholder="Doctor's Username" name="username">
					<input type="text" id="password" class="form-control" placeholder="Password" name= "password">

					<div class="text-md-right" >
						<small>Forgot <a href="#">Username/Password</a></small>
					</div>

					<!-- Login Button -->
					<div class="text-center">
						<button class="btn my-2 " id="submit-btn" type="submit">Login</button>
					</div>
				
					<hr>

					<div class="text-center">
						<span>New User? </span><a href="{% url 'doctor:registerpage' %}">Create an account</a>
					</div>
				</form>
				</div>
			</div>
    	</div>
    	<!--/.Content-->
    </div>

	<div class="slider"></div>
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<!--<script>
		document.getElementById("user").addEventListener("click",function()
		{
			document.querySelector(".popup").style.display="flex";
		})
	</script>-->



	<footer class="page-footer footer font-small mdb-color" style="background:linear-gradient(90deg, #24a19c,#cedebd);">

		<!-- Footer Links -->
		<div class="container text-center text-md-left">

			<!-- Footer links -->
			<div class="row text-center text-md-left mt-3">

				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none">
				<div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
					<h6 class="text-uppercase mb-2 font-weight-bold" >Useful links</h6>
					<p>
						<a href="{% url 'centralapp:Inside_health_records' %}" class="useful_links">What's in my health record</a><br>
						<a href="{% url 'centralapp:patients_how_to_use' %}" class="useful_links">How to use my health record</a><br>
						<a href="{% url 'centralapp:FAQS' %}" class="useful_links">FAQs</a>
					</p>
				</div>
				<!-- Grid column -->

				<!-- Grid column -->

				<hr class="w-100 clearfix d-md-none">

				<!-- Grid column -->

				<div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
					<h6 class="text-uppercase mb-2 font-weight-bold">Our Team</h6>
					<p>
						Madhav Mittal<br>
						HarshDeep Singh Kohli<br>
						Lavish Bansal<br>
						Shivangi Nayak
					</p>
				</div>
				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none">

				<!-- Grid column -->
				<div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
					<h6 class="text-uppercase mb-2 font-weight-bold">Contact</h6>
                    <p>
                        <i class="fa fa-home mr-3"></i>IIT(BHU), Varanasi, UP, India
                    </p>
                    <p>
                        <i class="fa fa-envelope mr-3 "></i> lavish.bansal.mat19@itbhu.ac.in
                    </p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> +91 9039276236
                    </p>

				</div>
				<!-- Grid column -->

			</div>
			<!-- Footer links -->

			<hr>

			<!-- Grid row -->
			<div class="row d-flex align-items-center">
				<!-- Grid column -->
				<div class="col-md-11 col-lg-11">
					<!--Copyright-->
					<p class="text-center">© 2020 Copyright:
						<strong> MedicDiary</strong>
					</p>
				</div>
			</div>
			<!-- Grid row -->

		</div>
		<!-- Footer Links -->
	</footer>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenMax.min.js" integrity="sha512-6MCPs9fbSIt6mTpJH2Lbo9Kk71gcgwY85BCqJGP04x+O08W3m/OiKfMiMc4VQKYn+DCtAQwpGumWeD0cACeRsQ==" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TimelineMax.min.js" integrity="sha512-MBKN+F1LTtgzsnhh92u6fEklbJbv13vKI/2BZP0LLR8+IMeqlp0h10R6afWaJv2HIJfTOQkjW0LCPrIFEkZVeg==" crossorigin="anonymous"></script>
	<!-- <script src="app.js"></script> -->
	<script type="text/javascript">
		const hero= document.querySelector(".hero")
		const slider= document.querySelector(".slider")
		const headline= document.querySelector(".headline")

		const tl= new TimelineMax();

		tl.fromTo(hero, 1, {height: "0%"}, {height: "100%", ease: Power2.easeInOut})
		.fromTo(hero,1.2, {width:"100%"}, {width:"80%",ease: Power2.easeInOut})
		.fromTo(slider,1,{x:"-100%"}, {x:"0%", ease: Power2.easeInOut},"-=1");

	</script>
</body>
</html>