MedicDiary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('centralapp.urls')),
    path('', include('doctor.urls')),
    path('', include('patient.urls')),
]

centralapp/urls.py
from . import views
from django.urls import path

app_name = 'centralapp'
urlpatterns = [

    path('',views.mainpage,name='mainpage'),
    path('About_us/',views.About_us,name ='About_us'),
    path('Aids/',views.Aids,name ='Aids'),
    path('Cancer/',views.Cancer,name ='Cancer'),
    path('Covid-19/',views.Covid_19,name ='Covid_19'),
    path('Diabetes/',views.Diabetes,name ='Diabetes'),
    path('FAQS/',views.FAQS,name ='FAQS'),
    path('Heart_disorder/',views.Heart_disorder,name ='Heart_disorder'),
    path('medical_practitioners/How_to_use',views.doc_how_to_use,name ='doc_how_to_use'),
    path('friends-and-family/How_to_use',views.patients_how_to_use,name ='patients_how_to_use'),
    path('Hypertension/',views.Hypertension,name ='Hypertension'),
    path('Inside_health_records/',views.Inside_health_records,name ='Inside_health_records'),    ]

doctor/urls.py
from . import views
from django.urls import path

app_name = 'doctor'
urlpatterns = [
      path('registerpage/',views.registerpage,name ='registerpage'),
       path('signup/',views.signup, name ='signup'),
         path('logind/',views.loginn, name ='logind'),
          path('myPatients/', views.myPatients, name='myPatients'),
      #     path('doctorProfile/', views.doctorProfile, name='doctorProfile'),
          path('addpatient/', views.addpatient, name='addpatient'),
          path('doctorRecords/<str:p>', views.doctorRecords, name='doctorRecords'),
           path('addRecord/', views.addRecord, name='addRecord'),
            path('newReport/', views.newReport, name='newReport'),
 

    path('doctorprofile/', views.doctor_profile, name='doctor_profile'),
   
   
   
    # path('doclogin/',views.doclogin,name ='doclogin'),
    # path('docregister/',views.docregister,name ='docregister')
]

patient/urls.py
from . import views
from django.urls import path

app_name = 'patient'
urlpatterns = [

    path('Medications/', views.medications, name='medications'),
    path('LabReports/', views.labreports, name='labreports'),
    path('patientProfile/', views.patientProfile, name='patientProfile'),
    path('patientRecords/', views.patientRecords, name='patientRecords'),
    path('personalNotes/', views.personalNotes, name='personalNotes'),
    
    
    # path('login/',views.login,name ='login'),
    path('registerpage/',views.registerpage,name ='registerpage'),
    path('signup/',views.signup, name ='signup'),
    path('loginp/',views.loginn, name ='loginp'),
    path('logout/',views.logout, name ='logout'),
    path('addnotes/',views.addnotes, name ='addnotes'),

]

patient/models.py
from django.db import models

class patient_details(models.Model):
    usertype=models.CharField(max_length=100,default="patient")
    fname=models.CharField(max_length=100)
    lname=models.CharField(max_length=100)
  
    username=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
  
    auth_key=models.CharField(max_length=100,default="123")


class notes(models.Model):
    username_p=models.CharField(max_length=100)
    description=models.TextField(max_length=10000)

patient/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.middleware.csrf import get_token


from .models import patient_details,notes
import random
import string

def get_random_string(length):
    # Random string with the combination of lower and upper case
    letters = string.ascii_letters
    result_str = ''.join(random.choice(letters) for i in range(length))
    print("Random string is:", result_str)


def patientProfile(request):
    return render(request, 'patient/patient_profile.html')
def patientRecords(request):
    return render(request, 'patient/patient_records.html')


def personalNotes(request):
    csrf_token = get_token(request)
    csrf_token_html = '<input type="hidden" name="csrfmiddlewaretoken" value="{}" />'.format(csrf_token)
    if request.user.is_authenticated:
        user=request.user
        if len(notes.objects.filter(username_p=user.username))==0:
            new_note=notes()
            new_note.username_p=user.username
            new_note.description='Add your notes here'
            new_note.save()

        note=notes.objects.get(username_p=user.username)
        return render(request, 'patient/personalNotes.html',{"des":note.description})
        

def labreports(request):
    return render(request, 'patient/labreports.html')
def medications(request):
    return render(request, 'patient/medications.html')

def registerpage(request):
    return render(request,'patient/register.html')

def signup(request):
    if request.method=="POST":
        fname=request.POST['fname']
        lname=request.POST['lname']
       
        username=request.POST['username']
        password=request.POST['password']
        email=request.POST['email']
       

        if len(username)>15:
            messages.error(request,'length of username should be less than15')
            return redirect('patient:registerpage')
        
        myuser=User.objects.create_user(username,email,password)
        myuser.first_name=fname
        myuser.last_name=lname
       
       
        myuser.save()
       
        print("1")

        patient=patient_details()
        patient.fname=fname
        patient.lname=lname
        patient.username=username
        patient.auth_key=get_random_string(8)
        patient.email=email
        patient.save()
        
        print('2')
        messages.success(request, 'Form submission successful')
        return redirect('/')
       

    else :
        return HttpResponse('404-not found')




def loginn(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            print("innn")
            request.session["username_p"]=username
            return render(request,'patient/patient_profile.html')

        else :
            print("invalid credentials")
            return render(request,'centralapp/mainpage.html')


        return HttpResponse('login')



    else:
        return HttpResponse('404-not found')

def logout(request):
    if request.method=="POST":
        logout(request)
        return render(request,'patient/mainpage.html') 
    return HttpResponse('logout')


def addnotes(request):
    if request.user.is_authenticated:
        user=request.user
        description=request.POST['description']
        username= user.username
        if len(notes.objects.filter(username_p=username))!=0:
            notes.objects.filter(username_p=username).delete()
            new_note=notes()
            new_note.username_p=username
            new_note.description=description
            new_note.save()
        else:
            new_note=notes()
            new_note.username_p=username
            new_note.description=description
            new_note.save()


        return redirect('patient:personalNotes')
        
       


    

patient/templates/patient/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Pacifico" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Cinzel" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Oswald"/>
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Grandstander"/>
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Ubuntu"/>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://kit.fontawesome.com/032a738741.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'patient/css_files/style.css' %}">
	<link rel="icon" type="image/png" href="{% static 'patient/Images/icon.png' %}"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
	<script src="{% static 'patient/js/app.js' %}"></script>
    <!--<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>-->
	<title>MedicDiary</title>
</head>
<body style="background: #f7f7ee">
	<script>
       AOS.init();
    </script>
	<nav class="navbar navbar-expand-lg navbar-light nav-bg" id="navstyle" >
		<a class="navbar-brand" href="{% url 'centralapp:mainpage' %}" style="font-family: Cinzel; font-size: 40px !important; color: white;" >
			<img src="{% static 'patient/Images/icon.png' %}" width="50" height="50" class="d-inline-block align-top" alt="" loading="lazy">
			MedicDiary
		</a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-size:20px; ">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item active">
					<a class="nav-link" href="#" style="color: rgb(0, 0, 0)"> Sign In </a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="#" style="color: rgb(0, 0, 0)"> Sign Up </a>
				</li>
			</ul>
		</div>
	</nav>
    
    
    <div id="sidebar" > 
        <div class="toggle-btn" onclick="toggleSideBar()">
            <span style='font-size:20px;'>&#9776;</span>
        </div>
    
        <ul>
            <a href="{% url 'patient:medications' %}"><li>Medication</li></a>
            <a href="{% url 'patient:labreports' %}"><li>Lab Reports</li></a>
            <a href="{% url 'patient:personalNotes' %}"><li>Personal notes</li></a>
            <a href="{% url 'patient:patientProfile' %}"><li>Edit your profile</li></a>
            <a href="{% url 'patient:patientRecords' %}"><li>Back to homepage</li></a>
        </ul>
    
    </div>

  {% block patient_base %}

  {% endblock %}


	<!-- Footer -->
	<footer class="page-footer footer font-small mdb-color" style="background:linear-gradient(90deg, #24a19c,#cedebd);">

		<!-- Footer Links -->
		

			<!-- Footer links -->
			<div class="row text-center ml-5 text-md-left mt-3">

				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none">
				<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
					<h6 class="text-uppercase mb-2 " >Know-hows</h6>
					<p>
						<a href="{% url 'centralapp:Inside_health_records' %}" class="useful_links">What's in my health record</a><br>
						<a href="{% url 'centralapp:patients_how_to_use' %}" class="useful_links">How to use my health record</a><br>
						<a href="{% url 'centralapp:doc_how_to_use' %}" class="useful_links">How to use the health record (for doctors)</a><br>
						<a href="{% url 'centralapp:FAQS' %}" class="useful_links">FAQs</a><br>
					</p>
				</div>
				<!-- Grid column -->
				<div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer-style">
					<h6 class="text-uppercase mb-2 font-weight-bold" > Other useful links</h6>
					<div class="no-bullet-list two-column-list">
						<a href="{% url 'centralapp:Covid_19' %}" class="useful_links">Covid-19 checkpoints</a><br>
						
						<h6 class="mt-2 font-weight-bold">Learn about diseases</h6>

						<ul>
						<li><a href="{% url 'centralapp:Cancer' %}" class="useful_links">Cancer</a><br></li>
						<li><a href="{% url 'centralapp:Aids' %}" class="useful_links">AIDS</a><br></li>
						<li><a href="{% url 'centralapp:Diabetes' %}" class="useful_links">Diabetes</a><br></li>
						<li><a href="{% url 'centralapp:Heart_disorder' %}" class="useful_links">Heart Disorders</a><br></li>
						<li><a href="{% url 'centralapp:Hypertension' %}" class="useful_links">Hypertension</a><br></li>

						</ul>
						</div>
					
				</div>
				<!-- Grid column -->

				<hr class="w-100 clearfix d-md-none">

				<!-- Grid column -->

				<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3 no-bullet-list footer-style">
					<h6 class="text-uppercase mb-2 font-weight-bold">Our Team</h6>
					<ul>
						<li>Madhav Mittal<br></li>
						<li>HarshDeep Singh Kohli<br></li>
						<li>Lavish Bansal<br></li>
						<li>Shivangi Nayak</li>
						</ul>
						<a href="{% url 'centralapp:About_us' %}" class="useful_links" style="font-weight:bold">More about us</a>
					
				</div>
				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none ">

				<!-- Grid column -->
				<div class="col-md-3 col-lg-3 col-xl-3 mr-5 mt-3 footer-style">
					<h6 class="text-uppercase mb-2 font-weight-bold ">Contact</h6>
                    <p>
                        <i class="fa fa-home mr-3"></i>IIT(BHU), Varanasi, UP, India
                    </p>
                    <p>
                        <i class="fa fa-envelope mr-3 "></i> madhav.mittal.mat19@itbhu.ac.in
                    </p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> +91 9039276236
                    </p>

				</div>
				<!-- Grid column -->

			</div>
			<!-- Footer links -->

			<hr>

			<!-- Grid row -->
			<div class="row d-flex align-items-center footer-style">
				<!-- Grid column -->
				<div class="col-md-11 col-lg-11">
					<!--Copyright-->
					<p class="text-center">© 2020 Copyright:
						<strong> MedicDiary</strong>
					</p>
				</div>
			</div>
			<!-- Grid row -->

		
		<!-- Footer Links -->
	</footer>

</body>
</html>

patient/templates/patient/mainpage.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Pacifico" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Cinzel" />
	<link rel="stylesheet"
	href="https://fonts.googleapis.com/css?family=Oswald"/>
	<link rel="stylesheet" href="{% static 'css_files/style.css' %}">
	<link rel="icon" type="image/png" href="{% static 'centralapp/Images/icon.png' %}"/>                            
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<title>MedicDiary</title>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light nav-bg" id="navstyle" >
		<a class="navbar-brand" href="{% url 'centralapp:mainpage' %}" style="font-family: Cinzel; font-size: 40px !important; color: white;" >
			<img src="{% static 'centralapp/Images/icon.png' %}" width="44" height="44" class="d-inline-block align-top" alt="" loading="lazy">
			MedicDiary
		</a>


		<div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-size:20px; ">

			<ul class="navbar-nav ml-auto">
				<li class="nav-item dropdown my-2 mx-1">
					<a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white">
						For you and<br> your family
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'centralapp:Inside_health_records' %}">What's in my health record </a>
						<a class="dropdown-item" href="{% url 'centralapp:patients_how_to_use' %}">How to use my health record </a>
					</div>
				</li>

				<li class="nav-item dropdown my-2 mx-1">
					<a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white">
						For healthcare<br>professionals
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'centralapp:doc_how_to_use' %}">How to use the health record</a>
					</div>
				</li>
				<li class="nav-item dropdown my-2 mx-1">
					<a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white">
						Know more<br>about diseases
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'centralapp:Aids' %}">AIDS</a>
						<a class="dropdown-item" href="{% url 'centralapp:Cancer' %}">Cancer</a>
						<a class="dropdown-item" href="{% url 'centralapp:Heart_disorder' %}">Heart Disorders</a>
						<a class="dropdown-item" href="{% url 'centralapp:Hypertension' %}">Hypertension</a>
						<a class="dropdown-item" href="{% url 'centralapp:Diabetes' %}">Diabetes</a>
						<a class="dropdown-item" href="{% url 'centralapp:Birth_control' %}">Birth Control Measures</a>
					</div>
				</li>
				<li>
					<a class="nav-link my-3 mx-1" style="color: white" href="{% url 'centralapp:FAQS' %}"> FAQs</a>
				</li>
				<li>
					<a class="nav-link my-3 mx-1" style="color: white" href="{% url 'centralapp:About_us' %}"> About us</a>
				</li>

				<li>
					<a href="{% url 'centralapp:Covid_19' %}" class="button2 mt-7 mx-1"> Covid-19 Checkpoints </a>
				</li>
			</ul>
		</div>
	</nav>

	<section>
		<div class="hero img">
			<a href="#" class="button" id="user" data-toggle="modal" data-target="#usermodal"> For you and your family </a>
			<a href="#" class="button" id= "doctor" data-toggle="modal" data-target="#doctormodal">For healthcare professionals </a>

			<img src="{% static 'centralapp/Images/bg2.jpg' %}">

			<h1 class="headline">One place for all <br> your health records. </h1>
			<p></p>
		</div>
	</section>
	<div class="modal fade" id="usermodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    	<div class="modal-dialog modal-notify modal-warning" role="document">
    		<!--Content-->
    		<div class="modal-content">
				<!--Header-->
				<div id="signincard" class="card" >
					<div id="cardhead" class="card-header bg-warning mb-2">
						<div class="card-title text-center h4">Sign In</div>
					</div>

					<!-- Input Fields -->
					<input type="text" id="username" class="form-control mb-2" placeholder="Patient's Username" name="username">
					<input type="text" id="password" class="form-control" placeholder="Password" name= "lname">

					<div class="text-md-right" >
						<small>Forgot <a href="#">Username/Password</a></small>
					</div>

					<!-- Login Button -->
					<div class="text-center">
						<button class="btn my-2" id="login" type="submit">Login</button>
					</div>

					<hr>

					<div class="text-center">
	##					<span>New User? </span><a href="{% url 'patient:registerpage' %}">Create an account</a>
					</div>
				</div>
			</div>
    		<!--/.Content-->
		</div>
	</div>

	<div class="modal fade" id="doctormodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  		<div class="modal-dialog modal-notify modal-warning" role="document">
			<!--Content-->
    		<div class="modal-content">
				<!--Header-->
				<div id="signincard" class="card" >
					<div id="cardhead" class="card-header bg-warning mb-2">
						<div class="card-title text-center h4">Sign In</div>
					</div>

					<!-- Input Fields -->
					<input type="text" id="username" class="form-control mb-2" placeholder="Doctor's Username" name="username">
					<input type="text" id="password" class="form-control" placeholder="Password" name= "lname">

					<div class="text-md-right" >
						<small>Forgot <a href="#">Username/Password</a></small>
					</div>

					<!-- Login Button -->
					<div class="text-center">
						<button class="btn my-2 " id="login" type="submit">Login</button>
					</div>

					<hr>

					<div class="text-center">
						<span>New User? </span><a href="#">Create an account</a>
					</div>
				</div>
			</div>
    	</div>
    	<!--/.Content-->
    </div>

	<div class="slider"></div>
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<!--<script>
		document.getElementById("user").addEventListener("click",function()
		{
			document.querySelector(".popup").style.display="flex";
		})
	</script>-->



	<footer class="page-footer footer font-small mdb-color" style="background:linear-gradient(90deg, #24a19c,#cedebd);">

		<!-- Footer Links -->
		<div class="container text-center text-md-left">

			<!-- Footer links -->
			<div class="row text-center text-md-left mt-3">

				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none">
				<div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
					<h6 class="text-uppercase mb-2 font-weight-bold" >Useful links</h6>
					<p>
						<a href="{% url 'centralapp:Inside_health_records' %}" class="useful_links">What's in my health record</a><br>
						<a href="{% url 'centralapp:patients_how_to_use' %}" class="useful_links">How to use my health record</a><br>
						<a href="{% url 'centralapp:FAQS' %}" class="useful_links">FAQs</a>
					</p>
				</div>
				<!-- Grid column -->

				<!-- Grid column -->

				<hr class="w-100 clearfix d-md-none">

				<!-- Grid column -->

				<div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
					<h6 class="text-uppercase mb-2 font-weight-bold">Our Team</h6>
					<p>
						Madhav Mittal<br>
						HarshDeep Singh Kohli<br>
						Lavish Bansal<br>
						Shivangi Nayak
					</p>
				</div>
				<!-- Grid column -->
				<hr class="w-100 clearfix d-md-none">

				<!-- Grid column -->
				<div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
					<h6 class="text-uppercase mb-2 font-weight-bold">Contact</h6>
                    <p>
                        <i class="fa fa-home mr-3"></i>IIT(BHU), Varanasi, UP, India
                    </p>
                    <p>
                        <i class="fa fa-envelope mr-3 "></i> lavish.bansal.mat19@itbhu.ac.in
                    </p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> +91 9039276236
                    </p>

				</div>
				<!-- Grid column -->

			</div>
			<!-- Footer links -->

			<hr>

			<!-- Grid row -->
			<div class="row d-flex align-items-center">
				<!-- Grid column -->
				<div class="col-md-11 col-lg-11">
					<!--Copyright-->
					<p class="text-center">© 2020 Copyright:
						<strong> MedicDiary</strong>
					</p>
				</div>
			</div>
			<!-- Grid row -->

		</div>
		<!-- Footer Links -->
	</footer>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenMax.min.js" integrity="sha512-6MCPs9fbSIt6mTpJH2Lbo9Kk71gcgwY85BCqJGP04x+O08W3m/OiKfMiMc4VQKYn+DCtAQwpGumWeD0cACeRsQ==" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TimelineMax.min.js" integrity="sha512-MBKN+F1LTtgzsnhh92u6fEklbJbv13vKI/2BZP0LLR8+IMeqlp0h10R6afWaJv2HIJfTOQkjW0LCPrIFEkZVeg==" crossorigin="anonymous"></script>
	<!-- <script src="app.js"></script> -->
	<script type="text/javascript">
		const hero= document.querySelector(".hero")
		const slider= document.querySelector(".slider")
		const headline= document.querySelector(".headline")

		const tl= new TimelineMax();

		tl.fromTo(hero, 1, {height: "0%"}, {height: "100%", ease: Power2.easeInOut})
		.fromTo(hero,1.2, {width:"100%"}, {width:"80%",ease: Power2.easeInOut})
		.fromTo(slider,1,{x:"-100%"}, {x:"0%", ease: Power2.easeInOut},"-=1");

	</script>
</body>
</html>

patient/templates/patient/personalNotes.html
{% extends 'patient/base.html' %}
{% load static %}
{% block patient_base %}
<div class="container" id="main-content">
<h1 style="font-family:'Ubuntu';font-size: 3rem;text-align: center; color: rgb(92, 46, 13); ">Personal Notes </h1>
<div style="display: flex; justify-content: center; text-align: center; color: rgb(184, 53, 53); font-size: 19px; ">
   
        Use this space to keep track some medicines or supplements you take without medical supervision. <br>
        Note that this information would be visible to the doctor maintaining your health record, however he won't be able to edit it.
</div>
<div style="display: flex; justify-content: center;">
    <form style="text-align: center;" action="{% url 'patient:addnotes' %}" method="POST">
        {% csrf_token %}
        <br>
        <textarea style="padding: 20px ;font-family: 'Grandstander';font-size: 20px;text-align: left;" rows="10" cols="80" name="description">
               {{des}}
             </textarea><br>
            <input style=" font-size: 18px;" class="edit-option-buttons" type="submit" value="Submit" />
    </form>
</div>
</div>
{% endblock %}